name: PHP Tests
on: [push, pull_request]

jobs:
  phpunit-and-phplint:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: "PHP-${{ matrix.php-versions }}: PHPUnit/phplint"
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:10, phplint
          extensions: redis

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Install dependencies
        run: composer install

      - name: Run phplint
        run: phplint --no-cache lib vendor

      - name: Install redis
        run: sudo apt-get install -y redis-server

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run PHPunit
        run: phpunit --configuration phpunit.xml.dist

  phpcs:
    if: false # Disable this job since there are too many coding style violations.
    runs-on: ubuntu-latest
    continue-on-error: true
    name: "PHPCS"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHPCS
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: cs2pr, phpcs

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Run PHPCS
        run: phpcs -q --report=checkstyle lib | cs2pr

  phpstan:
    runs-on: ubuntu-latest
    continue-on-error: false
    name: "PHPStan"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHPStan
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: phpstan

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Install dependencies
        run: composer install

      - name: Run PHPStan
        run: phpstan analyse lib --memory-limit=-1 -l1
